version: '3.6'

volumes:
  postgres_data:
    name: prod_movies_data
  static_volume:
    name: prod_static

networks:
  nginx_network:
    driver: bridge
  database_network:
    driver: bridge

services:

  db:
    image: postgres:13.0
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    networks:
      - database_network

  web:
    build: .
    container_name: movies_web
    restart: always
    volumes:
      - static_volume:/code/movies_admin/static
    command: >
            bash -c "cd movies_admin &&
            python3 manage.py migrate --noinput &&
            python3 manage.py collectstatic --noinput &&
            ../upload.sh &&
            gunicorn wsgi:application  --chdir config/ --log-level info --bind 0.0.0.0:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - nginx_network
      - database_network

  nginx:
    image: nginx:1.19.2
    container_name: nginx
    restart: always
    volumes:
      - static_volume:/code/movies_admin/static
      - ./movies_admin/src/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./movies_admin/src/site.conf:/etc/nginx/conf.d/site.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - nginx_network
